# Generated by Django 4.2.11 on 2024-06-27 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_alter_dispatchinstruction_po_no'),
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempackinginline',
            name='inline_item_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.inlineitemlist'),
        ),
    ]
