# Generated by Django 4.2.11 on 2024-04-30 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packing', '0002_boxdetails_loaded_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('exports_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('domestic_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('revision_no', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('box_size_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.boxsize')),
                ('box_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.boxtype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PackingPrice',
            },
        ),
    ]
