# Generated by Django 4.2.11 on 2024-04-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_packingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingprice',
            name='box_type_id',
        ),
    ]
