# Generated by Django 4.2.11 on 2024-04-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_remove_packingprice_box_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxdetails',
            name='box_type',
        ),
    ]
