# Generated by Django 4.2.11 on 2024-04-30 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_remove_inlineitemlist_master_item_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packing', '0005_remove_boxdetails_box_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPackingInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=300, null=True)),
                ('tag_no', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_pack_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_packing', to='packing.itempacking')),
                ('item_ref_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_list', to='dispatch.inlineitemlist')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ItemPackingInline',
            },
        ),
    ]
