# Generated by Django 4.2.11 on 2024-05-07 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_itempackinginline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempackinginline',
            name='item_pack_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_packing_inline', to='packing.itempacking'),
        ),
    ]
