# Generated by Django 4.2.11 on 2024-05-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0007_alter_itempackinginline_item_pack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxdetails',
            name='box_item_flag',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
