# Generated by Django 4.2.11 on 2024-04-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inlineitemlist',
            old_name='item_list_id',
            new_name='master_item_id',
        ),
    ]
