# Generated by Django 4.2.11 on 2024-06-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_dispatchinstruction_bill_to_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchinstruction',
            name='po_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
