# Generated by Django 4.2.11 on 2024-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_rename_item_list_id_inlineitemlist_master_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlineitemlist',
            name='packed_flag',
            field=models.BooleanField(default=False),
        ),
    ]
