# Generated by Django 4.2.11 on 2024-04-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_inlineitemlist_packed_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inlineitemlist',
            name='master_item_id',
        ),
        migrations.AddField(
            model_name='inlineitemlist',
            name='master_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_items', to='dispatch.masteritemlist'),
        ),
    ]
