# Generated by Django 4.2.11 on 2024-06-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_alter_dispatchinstruction_po_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchinstruction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispatchinstruction',
            name='customer_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
