# Generated by Django 4.2.11 on 2024-05-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_remove_inlineitemlist_master_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteritemlist',
            name='item_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masteritemlist',
            name='warranty_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masteritemlist',
            name='warranty_flag',
            field=models.BooleanField(default=False),
        ),
    ]
