# Generated by Django 4.2.11 on 2024-05-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_masteritemlist_item_no_masteritemlist_warranty_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteritemlist',
            name='so_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
