# Generated by Django 4.2.11 on 2024-05-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_masteritemlist_so_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchinstruction',
            name='dil_custom_so_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masteritemlist',
            name='custom_po_flag',
            field=models.BooleanField(default=False),
        ),
    ]
