# Generated by Django 4.2.11 on 2024-05-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_dispatchinstruction_dil_custom_so_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteritemlist',
            name='serial_no_qty',
            field=models.BooleanField(default=False),
        ),
    ]
