# Generated by Django 4.2.11 on 2024-05-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_masteritemlist_serial_no_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteritemlist',
            name='serial_no_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
