# Generated by Django 4.2.11 on 2024-05-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_alter_masteritemlist_serial_no_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchinstruction',
            name='updated_serial_flag',
            field=models.BooleanField(default=False),
        ),
    ]
