# Generated by Django 4.2.11 on 2024-05-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_dispatchinstruction_updated_serial_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteritemlist',
            name='packed_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
