# Generated by Django 4.2.11 on 2024-05-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_alter_masteritemlist_packed_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteritemlist',
            name='packed_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
