# Generated by Django 4.2.11 on 2024-05-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0013_dispatchpodetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteritemlist',
            name='status_no',
            field=models.IntegerField(default=0),
        ),
    ]
