# Generated by Django 4.2.11 on 2024-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0014_alter_masteritemlist_status_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteritemlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
