# Generated by Django 4.2.11 on 2024-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0015_alter_masteritemlist_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchinstruction',
            name='bill_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispatchinstruction',
            name='business_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
