# Generated by Django 4.2.11 on 2024-05-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0016_dispatchinstruction_bill_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteritemlist',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
