# Generated by Django 4.2.11 on 2024-05-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0019_dispatchinstruction_bill_to_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPInvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_doc_item', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_create_date', models.DateField(blank=True, null=True)),
                ('delivery_item', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_invoice_date', models.DateField(blank=True, null=True)),
                ('linkage_no', models.CharField(blank=True, max_length=100, null=True)),
                ('term_of_payment', models.CharField(blank=True, max_length=100, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('challan_create_date', models.DateField(blank=True, null=True)),
                ('challan_item', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_create_date', models.DateField(blank=True, null=True)),
                ('sales_currency', models.CharField(blank=True, max_length=100, null=True)),
                ('DIL_output_date', models.DateField(blank=True, null=True)),
                ('tax_invoice_assessable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_invoice_total_tax_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_invoice_total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SAPInvoiceDetails',
            },
        ),
    ]
