dil_upload_columns = ['Reference Document', 'Sold-to Party', 'Sold-to Party Name', 'Delivery',
                      'Delivery Create Date', 'Delivery Item', 'Tax Invoice Number (ODN)',
                      'Reference Document Item', 'MS Code', 'Quantity (Sales)',
                      'Linkage Number', 'Sales Office', 'Terms of Payment',
                      'Tax Invoice Date', 'Material Description', 'Plant', 'Plant Name',
                      'Unit (Sales)', 'Billing Number', 'Billing Create Date',
                      'Currency (Sales)', 'Ship-to party', 'Ship-to Party Name',
                      'Ship-to Country', 'Ship-to Postal Code', 'Ship-to City',
                      'Ship-to Street', 'Ship-to Street4', 'Insurance Scope',
                      'Sold-to Country', 'Sold-to Postal Code', 'Sold-to City',
                      'Sold-to Street', 'Sold-to Street4', 'Material Number', 'HS Code',
                      'HS Code Export', 'Delivery quantity', 'Unit (Delivery)',
                      'Storage Location', 'DIL Output Date', 'Sales Document Type',
                      'Distribution Channel', 'Invoice Item', 'Tax Invoice Assessable Value',
                      'Tax Invoice Total Tax Value', 'Tax Invoice Total Value',
                      'Item Price (Sales)', 'Packing status', 'DO Item Packed Quantity',
                      'Packed Quantity unit']


column_mapping = {
                'Reference Document': 'Reference Document',
                'Sold-to Party': 'Sold-to Party',
                'Sold-to Party Name': 'Sold-to Party Name',
                'Delivery': 'Delivery',
                'Delivery Create Date': 'Delivery Create Date',
                'Delivery Item': 'Delivery Item',
                'Tax Invoice Number (ODN)': 'Tax Invoice Number (ODN)',
                'Reference Document Item': 'Reference Document Item',
                'MS Code': 'MS Code',
                'Quantity (Sales)': 'Quantity (Sales)',
                'Linkage Number': 'Linkage Number',
                'Sales Office': 'Sales Office',
                'Terms of Payment': 'Terms of Payment',
                'Tax Invoice Date': 'Tax Invoice Date',
                'Material Description': 'Material Description',
                'Plant': 'Plant',
                'Plant Name': 'Plant Name',
                'Unit (Sales)': 'Unit (Sales)',
                'Billing Number': 'Billing Number',
                'Billing Create Date': 'Billing Create Date',
                'Currency (Sales)': 'Currency (Sales)',
                'Ship-to party': 'Ship-to party',
                'Ship-to Party Name': 'Ship-to Party Name',
                'Ship-to Country': 'Ship-to Country',
                'Ship-to Postal Code': 'Ship-to Postal Code',
                'Ship-to City': 'Ship-to City',
                'Ship-to Street': 'Ship-to Street',
                'Ship-to Street4': 'Ship-to Street4',
                'Insurance Scope': 'Insurance Scope',
                'Sold-to Country': 'Sold-to Country',
                'Sold-to Postal Code': 'Sold-to Postal Code',
                'Sold-to City': 'Sold-to City',
                'Sold-to Street': 'Sold-to Street',
                'Sold-to Street4': 'Sold-to Street4',
                'Material Number': 'Material Number',
                'HS Code': 'HS Code',
                'HS Code Export': 'HS Code Export',
                'Delivery quantity': 'Delivery quantity',
                'Unit (Delivery)': 'Unit (Delivery)',
                'Storage Location': 'Storage Location',
                'DIL Output Date': 'DIL Output Date',
                'Sales Document Type': 'Sales Document Type',
                'Distribution Channel': 'Distribution Channel',
                'Invoice Item': 'Invoice Item',
                'Tax Invoice Assessable Value': 'Tax Invoice Assessable Value',
                'Tax Invoice Total Tax Value': 'Tax Invoice Total Tax Value',
                'Tax Invoice Total Value': 'Tax Invoice Total Value',
                'Item Price (Sales)': 'Item Price (Sales)',
                'Packing status': 'Packing status',
                'DO Item Packed Quantity': 'DO Item Packed Quantity',
                'Packed Quantity unit': 'Packed Quantity unit'

            }
