# Generated by Django 4.2.11 on 2024-05-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subordinate', '0002_district_state_taluk_pincode_district_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='abbreviation',
        ),
    ]
