# Generated by Django 4.2.11 on 2024-06-24 05:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowAccess',
            fields=[
                ('wfa_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('auth_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), blank=True, default=list, size=None)),
                ('bill_type', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dept_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subdepartment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WorkflowAccess',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowControl',
            fields=[
                ('wfc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('approver', models.CharField(blank=True, max_length=150, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('parallel', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WorkflowControl',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowType',
            fields=[
                ('wf_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('wf_name', models.CharField(max_length=150, null=True)),
                ('slug_name', models.CharField(max_length=150, null=True)),
                ('total_level', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WorkflowType',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowEmployees',
            fields=[
                ('wfe_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('emp_type', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wfc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wfe', to='workflow.workflowcontrol')),
            ],
            options={
                'db_table': 'WorkflowEmployees',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowDeptEmp',
            fields=[
                ('wfde_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wfa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowaccess')),
            ],
            options={
                'db_table': 'WorkflowDeptEmp',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowDaApprovers',
            fields=[
                ('wfd_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('approver', models.CharField(max_length=150, null=True)),
                ('level', models.IntegerField(null=True)),
                ('parallel', models.BooleanField(null=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dil_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.dispatchinstruction')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowtype')),
            ],
            options={
                'db_table': 'WorkflowDaApprovers',
            },
        ),
        migrations.AddField(
            model_name='workflowcontrol',
            name='wf_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wfc', to='workflow.workflowtype'),
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='wf_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowtype'),
        ),
    ]
