# Generated by Django 4.2.11 on 2024-06-24 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subordinate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingTransportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_name', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TrackingTransportation',
            },
        ),
        migrations.CreateModel(
            name='TruckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_no', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('rating_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_in_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('check_out_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('gate_pass_no', models.IntegerField(default=0)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('loading_remarks', models.CharField(max_length=300, null=True)),
                ('delivered_datetime', models.DateTimeField(null=True)),
                ('loaded_flag', models.BooleanField(default=False)),
                ('loaded_date', models.DateTimeField(null=True)),
                ('tracking_status', models.IntegerField(default=0)),
                ('tracking_flag', models.IntegerField(default=0)),
                ('tracking_date', models.DateTimeField(null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('no_of_boxes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_out_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserTable', to=settings.AUTH_USER_MODEL)),
                ('transportation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.trackingtransportation')),
            ],
            options={
                'db_table': 'TruckList',
            },
        ),
        migrations.CreateModel(
            name='TruckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('remarks', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.district')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.state')),
                ('taluk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.taluk')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.trackingtransportation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TruckRequest',
            },
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type_name', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TruckType',
            },
        ),
        migrations.CreateModel(
            name='TruckRequestTypesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('truck_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.truckrequest')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_request_type_list', to='tracking.trucktype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TruckRequestTypesList',
            },
        ),
        migrations.CreateModel(
            name='TruckLoadingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dil_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.dispatchinstruction')),
                ('truck_list_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.trucklist')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TruckLoadingDetails',
            },
        ),
        migrations.AddField(
            model_name='trucklist',
            name='truck_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.truckrequest'),
        ),
        migrations.AddField(
            model_name='trucklist',
            name='truck_request_types_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.truckrequesttypeslist'),
        ),
        migrations.AddField(
            model_name='trucklist',
            name='truck_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.trucktype'),
        ),
        migrations.AddField(
            model_name='trucklist',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TruckDilMappingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dil_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.dispatchinstruction')),
                ('truck_list_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.trucklist')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TruckDilMappingDetails',
            },
        ),
        migrations.AddField(
            model_name='trackingtransportation',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.trucktype'),
        ),
        migrations.AddField(
            model_name='trackingtransportation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_way_bill_no', models.CharField(max_length=100, null=True)),
                ('lrn_no', models.CharField(max_length=100, null=True)),
                ('lrn_date', models.DateField(blank=True, null=True)),
                ('no_of_boxes', models.IntegerField(default=0)),
                ('remarks', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('truck_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.trucklist')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DeliveryChallan',
            },
        ),
        migrations.CreateModel(
            name='DCInvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=100, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_type', models.CharField(max_length=100, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_invoice_details', to='tracking.deliverychallan')),
                ('truck_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.trucklist')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DCInvoiceDetails',
            },
        ),
    ]
