# Generated by Django 4.2.11 on 2024-06-24 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcinvoicedetails',
            name='dil_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.dispatchinstruction'),
        ),
        migrations.AddField(
            model_name='dcinvoicedetails',
            name='so_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
