# Generated by Django 4.2.11 on 2024-04-29 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subordinate', '0002_district_state_taluk_pincode_district_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('remarks', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.district')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.pincode')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.state')),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.taluk')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.trackingtransportation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TruckRequest',
            },
        ),
        migrations.CreateModel(
            name='TruckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_no', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('ratingRemarks', models.CharField(blank=True, max_length=200, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_in_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('check_out_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('loading_remarks', models.CharField(max_length=300, null=True)),
                ('delivered_datetime', models.DateTimeField(null=True)),
                ('loaded_flag', models.BooleanField(default=False)),
                ('loaded_date', models.DateTimeField(null=True)),
                ('tracking_status', models.IntegerField(default=0)),
                ('tracking_flag', models.IntegerField(default=0)),
                ('tracking_date', models.DateTimeField(null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserTable', to=settings.AUTH_USER_MODEL)),
                ('transportation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.trackingtransportation')),
                ('truck_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.truckrequest')),
                ('truck_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.trucktype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TruckList',
            },
        ),
    ]
