# Generated by Django 4.2.11 on 2024-06-24 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_dcinvoicedetails_dil_id_dcinvoicedetails_so_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='consignee_remakes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='description_of_goods',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='freight_mode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='kind_attended',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='mode_of_delivery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceChequeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cheque_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_no', models.CharField(max_length=100, null=True)),
                ('cheque_no', models.CharField(max_length=100, null=True)),
                ('cod_cheque_received_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_withdrawal_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dc_invoice_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_cheque_details', to='tracking.dcinvoicedetails')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'InvoiceChequeDetails',
            },
        ),
    ]
