# Generated by Django 4.2.11 on 2024-04-29 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0003_rename_ratingremarks_trucklist_rating_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckRequestTypesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transportation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.trackingtransportation')),
                ('truck_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.truckrequest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TruckRequestTypesList',
            },
        ),
        migrations.AddField(
            model_name='trucklist',
            name='truck_request_types_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.truckrequesttypeslist'),
        ),
    ]
