# Generated by Django 4.2.11 on 2024-04-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_remove_inlineitemlist_master_item_id_and_more'),
        ('tracking', '0005_truckloadingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckloadingdetails',
            name='dil_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.dispatchinstruction'),
        ),
    ]
