# Generated by Django 4.2.11 on 2024-05-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_alter_dcinvoicedetails_delivery_challan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcinvoicedetails',
            name='delivery_challan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_invoice_details', to='tracking.deliverychallan'),
        ),
    ]
