# Generated by Django 4.2.11 on 2024-05-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_dcinvoicedetails_delivery_challan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucklist',
            name='no_of_boxes',
            field=models.IntegerField(default=0),
        ),
    ]
