# Generated by Django 4.2.11 on 2024-05-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_alter_truckrequest_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckrequesttypeslist',
            name='transportation',
        ),
        migrations.AddField(
            model_name='truckrequesttypeslist',
            name='truck_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.trucktype'),
        ),
    ]
