# Generated by Django 4.2.11 on 2024-05-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_remove_truckrequesttypeslist_transportation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckrequesttypeslist',
            name='truck_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='truck_request_type_list', to='tracking.trucktype'),
            preserve_default=False,
        ),
    ]
