# Generated by Django 4.2.11 on 2024-05-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_alter_truckrequesttypeslist_truck_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucklist',
            name='gate_pass_no',
            field=models.IntegerField(default=0),
        ),
    ]
