# Generated by Django 4.2.11 on 2024-05-10 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0014_trucklist_gate_pass_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucklist',
            name='check_out_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
