# Generated by Django 4.2.11 on 2024-05-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subordinate', '0003_remove_state_abbreviation'),
        ('tracking', '0015_trucklist_check_out_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckrequest',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.district'),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.state'),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='taluk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.taluk'),
        ),
    ]
