# Generated by Django 4.2.11 on 2024-05-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_alter_truckrequest_district_alter_truckrequest_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckrequest',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
