# Generated by Django 4.2.11 on 2024-05-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_alter_truckrequest_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
