# Generated by Django 4.2.11 on 2024-05-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_deliverychallan_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='consignee_remakes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='description_of_goods',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='freight_mode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='kind_attended',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='mode_of_delivery',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
