# Generated by Django 4.2.11 on 2024-05-31 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0020_sapinvoicedetails'),
        ('tracking', '0019_deliverychallan_consignee_remakes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcinvoicedetails',
            name='dil_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.dispatchinstruction'),
        ),
        migrations.AddField(
            model_name='dcinvoicedetails',
            name='so_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceChequeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cheque_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_no', models.CharField(max_length=100, null=True)),
                ('cheque_no', models.CharField(max_length=100, null=True)),
                ('cod_cheque_received_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_withdrawal_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dc_invoice_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_cheque_details', to='tracking.dcinvoicedetails')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'InvoiceChequeDetails',
            },
        ),
    ]
